# Generated by Django 6.0.4 on 2026-05-10 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='crm_lead_id',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='ID лида в Bitrix24'),
        ),
    ]
